version: "3"

services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - "5000:5000"

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27018:27017"
